backend:
  name: github
  repo: fabifors/irsvp

media_folder: 'static/uploads'
public_folder: '/uploads'

collections:
  - name: 'posts'
    label: 'Posts'
    folder: 'posts'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Summary', name: 'summary', widget: 'string' }
      - { label: 'Author', name: 'author', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'date' }
      - { label: 'Content', name: 'content', widget: 'markdown' }
      - { label: 'Tags', name: 'tags', widget: 'select' }
